import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/Header';
import Footer from '@/components/Footer';
/*import { Inter } from '@next/font/google'*/
/*import styles from '@/styles/Home.module.css'*/

/*const inter = Inter({ subsets: ['latin'] })*/

export default function Home() {
  return (
    <>
      <Head>
        <title>Preguntas Técnicas de Entrevista</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="public/img/favicon/favicon-32x32.png"
        />
        
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0 shrink-to-fit=no"
        />
        
      </Head>
     <Header />

      <section className="hero-banner home-hero">
        <div className="hero-banner-img">
          <Image  alt="" width={1600} height={500} src={'/img/home/Banner-home-color.png'} />
          <figcaption className="hero-banner-caption pb-1">
            <div className="container">
              <div className="row">
                <div className="col-12 col-lg-8 offset-lg-2">
                  <h4 className="t-uni-heavy-italic"></h4>
                </div>
                <div className="col-12 col-lg-8 offset-lg-2">
                  <h1 className="t-uni-heavy-italic mt-1 bla">
                    Preguntas Técnicas de Entrevista
                  </h1>
                </div>
                <div className="col-12 col-lg-8 offset-lg-2">
                  <h4 className="t-uni-heavy-italic"></h4>
                </div>
                <div className="col-12 col-lg-8 offset-lg-2">
                  <p className="p-uni-regular bla">
                    Estas son las preguntas más comúnes si estas aplicando para
                    una vacante de:
                  </p>
                  <div className="hero-menu p-uni-regular">
                    <ul>
                      <li>
                        <a href="/pages/DesarrolloFullStackJavascript/">
                          Desarrollo Full Stack JavaScript
                        </a>
                      </li>
                      <li>
                        <a href="/DesarrolloFrontEnd/">
                          Desarrollo Front End
                        </a>
                      </li>
                      <li>
                        <a href="/DataScience/">
                          Data Science
                        </a>
                      </li>
                      <li>
                        <a href="/DisenoUXUI/">
                          Diseño UX/UI
                        </a>
                      </li>
                      <li>
                        <a href="/DataAnalytics/">
                          Data Analytics
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </figcaption>
        </div>
      </section>
      <section className="unete-cursos bg-na">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <div className="unete-cursos-content">
                <div className="row">
                  <div className="col-12 col-md-8">
                    <div className="unete-cursos-left">
                      <p className="p-uni-heavy-italic">
                        *Tú puedes ser el próximo
                      </p>
                      <p className="p-uni-regular">
                        <span id="carreras-type">Desarrollador Full</span>
                        <span className="typed-cursor">|</span>
                      </p>
                    </div>
                  </div>
                  <div className="col-12 col-md-4">
                    <div className="unete-cursos-right">
                      <a
                        className="btn-b-na"
                        href="https://desafiolatam.com/#box-courses"
                      >
                        <code>&lt;&lt;</code>Únete<code>&gt;&gt;</code>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="cursos-home" id="cta-bottom">
        <div className="container">
          <h2 className="t-uni-italic bla">
            <code>&lt;</code>Carreras Disponibles<code>&gt;</code>
          </h2>
          <div className="row m-0">
            <div className="col-12 col-md-6 col-xl-4">
              <div className="cursos-home-content bg-am">
                <h3 className="t-uni-heavy-italic">/*DESARROLLO</h3>
                <h3 className="t-uni-heavy-italic">FULL STACK JAVASCRIPT*/</h3>
                <p>
                  Genera las competencias necesarias para sumarte a un equipo de
                  desarrollo, aprende a desarrollar aplicaciones web con Node.js
                  desde cero.
                </p>

                <a href="https://desafiolatam.com/full-stack-javascript/">
                  leer + &gt;
                </a>
              </div>
            </div>

            <div className="col-12 col-md-6 col-xl-4">
              <div className="cursos-home-content bg-ne">
                <h3 className="t-uni-heavy-italic">/*DESARROLLO</h3>
                <h3 className="t-uni-heavy-italic">FRONT END REACT*/</h3>
                <p>
                  Genera las competencias para trabajar en la capa cliente de un
                  equipo de desarrollo de aplicaciones web dominando HTML, CSS,
                  JavaScript y el framework React.
                </p>

                <a href="https://desafiolatam.com/front-end-react/">
                  leer + &gt;
                </a>
              </div>
            </div>

            <div className="col-12 col-md-6 col-xl-4">
              <div className="cursos-home-content bg-ve-o">
                <h3 className="t-uni-heavy-italic">/*DATA</h3>
                <h3 className="t-uni-heavy-italic">SCIENCE*/</h3>
                <p>
                  Súmate al mundo de la ciencia de datos. Aprenderás
                  programación orientada a estadística, visualización de datos,
                  Machine Learning y SQL.
                </p>

                <a href="https://desafiolatam.com/data-science/">leer + &gt;</a>
              </div>
            </div>

            <div className="col-12 col-md-6 col-xl-4">
              <div className="cursos-home-content bg-ce">
                <h3 className="t-uni-heavy-italic">/*DISEÑO</h3>
                <h3 className="t-uni-heavy-italic">UX/UI*/</h3>
                <p>
                  Aprende a crear experiencias de usuarios desde la
                  investigación, la ideación, el diseño visual, la construcción
                  de prototipos, la implementación y la evaluación.
                </p>

                <a href="https://desafiolatam.com/diseno-ux-ui/">leer + &gt;</a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  )
}
